### ISSUE TITLE
没有判断meta_url2响应状态 导致生成秒传链接时卡住

### ISSUE THREAD

**Issue by rubnet** [mengzonefire/my_web_script#1]
[没有判断 r.status ](https://github.com/mengzonefire/my_web_script/blob/main/%E7%A7%92%E4%BC%A0%E9%93%BE%E6%8E%A5%E6%8F%90%E5%8F%96/%E7%A7%92%E4%BC%A0%E9%93%BE%E6%8E%A5%E6%8F%90%E5%8F%96(es6).js#L621) 当接口出错（返回的可能不是json字符串）时， 导致生成秒传时卡住

**Comment by mengzonefire** [comment]
正在重构代码, 会把状态码检查统一加到请求内的
